const rawData = [
    // 台北市
    { store: "Funbox 天母三越店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/wBvFN2J" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/VwXtHSw" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/qt4wA06" },
    { store: "Funbox 天母三越店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/7pFR6OL" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/nlNO7zU" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/PIePz1a" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/uaBy3wh" },
    { store: "Funbox 天母三越店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/OnkeSxw" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/yAnYvar" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/sjANMnS" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/yDuMJqF" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/O6A5Qu4" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/x9ejtfu" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/uiraH5M" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7wo6hoR" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/t5DzC6W" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/tn0jSx7" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/oQftDUW" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/z7Td3Gr" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/8WUY2KX" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/7OSuRof" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/rwPDcO1" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/8UeJWKh" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/OPYEc578" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/WBMWFcS" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/RxHvaPM" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/NzS2cxEK" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/tvERf3U" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/vjuf0wr" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/NYvqvZ2" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/ZAbzxDV" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/SE0DFSI" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/87xUH1V" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/8fEeQs2" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/NWIqavM" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/NX0u6zt" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/Wdlwq4x" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/YaNp2ax" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/x2sZbiB" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/qiUdBhv" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/yXW2ZaV" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/T0Bn5jo" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/Noblk6Sa" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Pwc4Tl2" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/xHpCF14" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/qxwwrT2" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/zCmUo3W" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/7GvvFzA" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/ZVKVm1g" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/6Jb8Xeq" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/opnUKNC" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7a1iQAm" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/TUn3Y7o" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/orJ6uyC" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xe0367ja" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/xxqkyvC" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/TmhBnu9" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/9xvdY8S" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/yP3r8Lq" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/tratm8F" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/zrGLkVA" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/QrlSYOm" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/suYW8By" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/XoUgnBE" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/zTfTvpD" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/zBGbaSa" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/NmI5pyX" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5iP45eb" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/X1Ypoek" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/OXTR7l3" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/S8yfj1o" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/ZOZ34q6" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/ZHURiDd" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/t9Fn7iw" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/tNvOVbj" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/yio9ZGk" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/WeVBkyE" },
    // 屏東縣
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xXc9byqC" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/qJ1UOcE" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/uHV4RnV" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/ZtaDmqq" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/rNcEPJi" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/x9GFgLdM" },
    // 新北市
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/NZhMQ4x" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/UMZIIXH" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/r5My0c3" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/sOWP5E27" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/PBP4vgc" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/T003MNz" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/oL6Aqh7" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/nIkFU1w" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/57jq5sG" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/SR4uIfA" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/VBlLELk" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/UpULXTP" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/5zFKgpP" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/S4uOZ39" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/sTP2QCw" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/yNH9nGh" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/yHG2AoXK" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/stOnQIN" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/sFPY1KT" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/wSSyb6O" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/XeIJeWC" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/pM2tdPFu" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/OSj26JJ" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/StkURkyV" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/wjRuEzM" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/S2hCveN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/Rka7bKF" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/qX1qW6ar" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/SUqCHvm" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/Op8jS9I" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/9lxk0P4R" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/RsQCHAX1" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/zSArdFn" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/qXJgkTI" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/wQnsGbN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/OW8V3OF" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/VCgeEGN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/YY093fd" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/o1RgS8q" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/tnp36hW" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/nGikFntS" },
    { store: "Funbox 中和環球店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/ufiWrfX" },
    { store: "Funbox 中和環球店", region: "新北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/TEak2ba" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/tkvs2R4" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/o2UyqHH" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/96NCPQM" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/UzR2ljE" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/Y05Wj8Y" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/Qvbk3nN" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/VLh1vvg" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/qBG4FaP" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/8IIXGfM" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/wF4KXAF" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/OpaV6iw" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/QjRGGvY" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/7c1CEKX" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/PGysA24" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/zkA1diW" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/6AW4HFq" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/Xg4XnVj" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/pYB3npJf" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5l2uJTo" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/To1hX0R" },
    // 台中市
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/5ElqgKur" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/pRMKio6" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/sN6CwOV" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/Qr85ude" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/S1Hshg7" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/760o35A" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/n3TPmTn" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/UICzg33" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/S1dOPWk" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/QjhI9MP" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/OtVbNFm" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/pmfKR4L" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/zGvMqnX" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/8V9g0ju" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/tbARevuY" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7PAip29" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/PLQYVpm" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/RUJjSVC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/6VmsizF" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/P7fw5aM" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/5Ke8LGi" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/xXegem6" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/RiAlVw2" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/VjVuOKz" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/W3iWsdI" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/w0xmLqC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/XTgMC8r" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/X2LfqUV" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/omF0FgC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/Wa89sUG" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/tYg9wIb" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/snLupZo" },
    // 嘉義市
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/RzrueWr" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/n4lh588" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/WJScw52" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/uWjWAo1" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/zx9seKT" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/RdWwrdUn" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XptkWBX" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/uIAKrOm" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/ybPJQ0u" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/pjDJ7QO" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/nKCSoTk" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/y9P4W2w" },
    // 台東縣
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/rx77vSI" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-45 武士魂斬", url: "https://lin.ee/7L2ZwBZ" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/Ndt9rS0" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/WuDoM99" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/NiUGZMC" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/UrVGwEH" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/9lWh4md" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Vcn8lNE" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/wWKv6iu" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-33 皓戰猛虎", url: "https://lin.ee/TYbeO2D" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/6Fhvtq5" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XpySyBv" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-26 獨角刺心", url: "https://lin.ee/Z2SzqqaH" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-18 X旋風發射器", url: "https://lin.ee/T98JtYO" },
    // 新竹市
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/XgQ7Frk" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/VHCI3nV" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/RusLNjiQ" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/vXHogcq" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/Wy5ANhK" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/PDuEWPU" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/z8SP0Fc" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/oFWfevv" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/zpKVnDo" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/8yA5lm6" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/7Dc5Y3x" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/6dwXuN0" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/nBfAH4d" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/sxB3FS5" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/RxZbvrr" },
    // 桃園市
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/PMfRxsS" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-18 X旋風發射器", url: "https://lin.ee/UJOyslk" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-26 獨角刺心", url: "https://lin.ee/Oya4wBN" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/XQtg8KH" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/WHbtrMP" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/W7a5GSM" },
];
