var rawData = [
    // 台北市
    { store: "Funbox 天母三越店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/wBvFN2J" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/VwXtHSw" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/qt4wA06" },
    { store: "Funbox 天母三越店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/7pFR6OL" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/nlNO7zU" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/PIePz1a" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/uaBy3wh" },
    { store: "Funbox 天母三越店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/OnkeSxw" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/yAnYvar" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/sjANMnS" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/yDuMJqF" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/O6A5Qu4" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/x9ejtfu" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/uiraH5M" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7wo6hoR" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/t5DzC6W" },
    { store: "Funbox 天母三越店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/tn0jSx7" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/oQftDUW" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/z7Td3Gr" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/8WUY2KX" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/7OSuRof" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/rwPDcO1" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/8UeJWKh" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/OPYEc578" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/WBMWFcS" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/RxHvaPM" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/NzS2cxEK" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/tvERf3U" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/vjuf0wr" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/NYvqvZ2" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/ZAbzxDV" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/SE0DFSI" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/87xUH1V" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/8fEeQs2" },
    { store: "Funbox 大葉高島屋店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/NWIqavM" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/Tsf3qzM" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/X0iqskqS" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/WmNoUHa" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/qgD1PMc" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/WCfm9dX" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/RpJPUZw" },
    { store: "Funbox 信義A8店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/6EgSqUS" },
    { store: "Funbox 信義A8店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/PRItKmN" },
    { store: "Funbox 信義A8店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/o9jTJmJ" },
    { store: "Funbox 信義A8店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/OiJG4ER" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/NX0u6zt" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/Wdlwq4x" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/YaNp2ax" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/x2sZbiB" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/qiUdBhv" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/yXW2ZaV" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/T0Bn5jo" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/Noblk6Sa" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Pwc4Tl2" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/xHpCF14" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/qxwwrT2" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/zCmUo3W" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/7GvvFzA" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/ZVKVm1g" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/6Jb8Xeq" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/opnUKNC" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7a1iQAm" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/TUn3Y7o" },
    { store: "Funbox 南港潤泰店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/orJ6uyC" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xe0367ja" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/xxqkyvC" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/TmhBnu9" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/9xvdY8S" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/yP3r8Lq" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/tratm8F" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/zrGLkVA" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/QrlSYOm" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/suYW8By" },
    { store: "Funbox 忠孝SOGO店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/XoUgnBE" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/zTfTvpD" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/zBGbaSa" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/NmI5pyX" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5iP45eb" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/X1Ypoek" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/OXTR7l3" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-00 暴風天馬", url: "https://lin.ee/S8yfj1o" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/ZOZ34q6" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/ZHURiDd" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/t9Fn7iw" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/tNvOVbj" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/yio9ZGk" },
    { store: "來玩聚 北車地下街店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/WeVBkyE" },
    { store: "Funbox 三越站前店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/XPI38YQE" },
    { store: "Funbox 三越站前店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/xxBXwm8" },
    { store: "Funbox 三越站前店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/VsLOyOe" },
    { store: "Funbox 三越站前店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/Yu0oI9O" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/QKy5qn7" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/PzRjMLL" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/roNvWF1" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/vBSvCHb" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/vRy7Kmb" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/WrnejoZ" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/pbZhX9A" },
    { store: "Funbox 天母SOGO店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/5JE24Ce" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/rmqmcJK" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/OTcb95I" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/p1ae3r1" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/qrLVL4d" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/qO377rA" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/6JxC0z7" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/sIwKwXDU" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/xbiVtHb" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/TiVMoAc" },
    { store: "Funbox 遠百信義A13店", region: "台北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/TZt71nw" },
    { store: "Funbox 美麗華店", region: "台北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/WcqjWdy" },
    { store: "Funbox 美麗華店", region: "台北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/uDrqsH5" },
    { store: "Funbox 美麗華店", region: "台北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/wlBvX5F" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/wq8Xh16" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/UMF2FOh" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/o6FCEYD" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-26 獨角刺心", url: "https://lin.ee/VXF1Iub" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/ULt1jCP" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/WZOYsDS" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/WEOWkxg" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/7QwGv71" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-45 武士魂斬", url: "https://lin.ee/SQmvkTm" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/NsXneVi" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/oBrBdCY" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/oRVQpRZ" },
    { store: "Funbox 美麗華店", region: "台北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/tJBIH2W" },
    // 高雄市
    { store: "Funbox 大魯閣新光店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/XxiuZV7" },
    { store: "Funbox 大魯閣新光店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/PFcrETG" },
    { store: "Funbox 大魯閣新光店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/rbKefO7" },
    { store: "Funbox 大魯閣新光店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/PoOO5Wd" },
    { store: "Funbox 高雄sogo店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/9CnBTJZ" },
    { store: "Funbox 高雄sogo店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/vKSysQe" },
    { store: "Funbox 高雄sogo店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/8MBpgBk" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/NXpwWvL" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/5XlGjqt" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/yOvvsVK" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/RJdDWRk" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/uoKpTEl" },
    { store: "Funbox 高雄大立店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/ZNECVAe" },
    { store: "Funbox 夢時代店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/PZwM3hv" },
    { store: "Funbox 夢時代店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/vsY1yZCk" },
    { store: "Funbox 夢時代店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/XIt0quy" },
    { store: "Funbox 夢時代店", region: "高雄市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/nQgavSq" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/yqDYC8F" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/zqUwsPd" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/XTB9gUM" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/WlkvAUb" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/UXHrX2B" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/TxHbFEz" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-45 武士魂斬", url: "https://lin.ee/YxSiUzQ" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/yO5HQJY" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/tgSQ16I" },
    { store: "Funbox 漢神巨蛋店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/uqGwU7k" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/U0PgSDH" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/teBbPGH" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-26 獨角刺心", url: "https://lin.ee/S1v2vw5" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/WxXWXvZ" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-18 X旋風發射器", url: "https://lin.ee/NiixCsHK" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/t58dMIJ" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/wxWzgGC" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/u3f7OTL" },
    { store: "來玩聚 新楠店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/qTQz1ei" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/w8dXvxe" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/n7wJHPf" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/9hQDNOH" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/Uo0LIS0" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/rA22gXs" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/t0mX19D" },
    { store: "來玩聚 楠梓店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/zaMvKH5P" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-45 武士魂斬", url: "https://lin.ee/qMlelu4" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/6JJJ9Kv" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/xmqs6s81" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/TEpz5Ht" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/Xe7KE2x5" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/xFOkeAW" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/8HsN6Cp" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Tne7NHQ" },
    { store: "Funbox 義大2館店", region: "高雄市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/VDkvXe8" },
    // 新北市
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/NZhMQ4x" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/UMZIIXH" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/r5My0c3" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/sOWP5E27" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/PBP4vgc" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/T003MNz" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/oL6Aqh7" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/nIkFU1w" },
    { store: "Funbox 新店誠品店", region: "新北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/57jq5sG" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/SR4uIfA" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/VBlLELk" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/UpULXTP" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/5zFKgpP" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/S4uOZ39" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/sTP2QCw" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/yNH9nGh" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/yHG2AoXK" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/stOnQIN" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/sFPY1KT" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/wSSyb6O" },
    { store: "Funbox 樹林秀泰店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/XeIJeWC" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/Y05Wj8Y" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/Qvbk3nN" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/VLh1vvg" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/qBG4FaP" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/8IIXGfM" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/wF4KXAF" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/OpaV6iw" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/QjRGGvY" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/7c1CEKX" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/PGysA24" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/zkA1diW" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/6AW4HFq" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/Xg4XnVj" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/pYB3npJf" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5l2uJTo" },
    { store: "Funbox 板橋遠東店", region: "新北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/To1hX0R" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/pM2tdPFu" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/OSj26JJ" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/StkURkyV" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/wjRuEzM" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/S2hCveN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/Rka7bKF" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/qX1qW6ar" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/SUqCHvm" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/Op8jS9I" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/9lxk0P4R" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/RsQCHAX1" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/zSArdFn" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/qXJgkTI" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/wQnsGbN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/OW8V3OF" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/VCgeEGN" },
    { store: "Funbox 汐止遠雄店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/YY093fd" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/o1RgS8q" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/tnp36hW" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/nGikFntS" },
    { store: "Funbox 中和環球店", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/ufiWrfX" },
    { store: "Funbox 中和環球店", region: "新北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/TEak2ba" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/tkvs2R4" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/o2UyqHH" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/96NCPQM" },
    { store: "Funbox 中和環球店", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/UzR2ljE" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-00 暴風天馬", url: "https://lin.ee/xheASvX" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/seyqhlS" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-18 X旋風發射器", url: "https://lin.ee/UwnH92e" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-26 獨角刺心", url: "https://lin.ee/pkDSIq5" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/R6VQbEl" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/rNAmAgV" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/Y3gWQVr" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/sSNr3M8" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/z7kLKuv6" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/TsnvZ4M" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/qcpfI4D" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5mYI87f" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "UX-01 蒼龍爆刃", url: "https://lin.ee/nno3V7j" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XjabcZaU" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/PtcBTDnb" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/nhavyh4" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/8PXerlh" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/s8ZDxf1" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/p1SwEvf" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-45 武士魂斬", url: "https://lin.ee/6pTWBQKN" },
    { store: "Funbox 板橋大遠百", region: "新北市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/qTLQJZR" },
    // 屏東縣
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xXc9byqC" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/qJ1UOcE" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/uHV4RnV" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/ZtaDmqq" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/rNcEPJi" },
    { store: "Funbox 屏東太平洋店", region: "屏東縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/x9GFgLdM" },
    { store: "Funbox 屏東環球店", region: "屏東縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/ZObGgAg" },
    { store: "Funbox 屏東環球店", region: "屏東縣", name: "BX-45 武士魂斬", url: "https://lin.ee/oAUbdUO" },
    { store: "Funbox 屏東環球店", region: "屏東縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/s6BrZTU" },
    { store: "Funbox 屏東環球店", region: "屏東縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/WwhexSJ" },
    // 台中市
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/5ElqgKur" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/pRMKio6" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/sN6CwOV" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/Qr85ude" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/S1Hshg7" },
    { store: "Funbox 麗寶一期店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/760o35A" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/u0Y0AmI" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/Rdm6dIG" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/UUQ68s0" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/nfE6YpW" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/ST2wbmi" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/wt7ZN3z" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/7ZaToqn" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/7CdsZLv" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-45 武士魂斬", url: "https://lin.ee/t4OJ2UN" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/qiV9cNm" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xeNSl1i" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/6Ug3BP7" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/7FKDLby" },
    { store: "Funbox 台中中友店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/QptFYwJ" },
    { store: "Funbox 台中中友店", region: "台中市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/sfMgKmZ" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/ZoRMNno" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/PazsXZR" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/W4i4zJG" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/Udwwj2L" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/uBo4rvL" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/RqUsm85" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/PWOHTju" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/tg1LB7K" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-45 武士魂斬", url: "https://lin.ee/6v6rB8l" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/QQaFt8F" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/SsQcVGJ" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/YJzAq52" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/tBApiM8" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/yuMDan0" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/p213YpN" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Wo4vwGH" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/ukxITe9" },
    { store: "Funbox 台中遠百店", region: "台中市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/ppsPrIS4" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/n3TPmTn" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/UICzg33" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/S1dOPWk" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/QjhI9MP" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/OtVbNFm" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/pmfKR4L" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/zGvMqnX" },
    { store: "Funbox 台中港三井店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/8V9g0ju" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/tbARevuY" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/7PAip29" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/PLQYVpm" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/RUJjSVC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/6VmsizF" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/P7fw5aM" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/5Ke8LGi" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/xXegem6" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/RiAlVw2" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/VjVuOKz" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/W3iWsdI" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/w0xmLqC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/XTgMC8r" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/X2LfqUV" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/omF0FgC" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/Wa89sUG" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/tYg9wIb" },
    { store: "Funbox 廣三SOGO店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/snLupZo" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/9d8fh4t" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/OrDhGF5" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/v8H81Hp" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/q6IRMoJ" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/9va1Ept" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/sGmIqhI" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/7cQpFng" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/6TBJaAM" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "UX-03 魔導神杖", url: "https://lin.ee/WhA1YMF" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/rTUxOCT" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/SzdgXPy" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/WQncIAy" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/xejG4ag" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/RywHgiK" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/6Xmqwex" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-45 武士魂斬", url: "https://lin.ee/NAuyK4O" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/qOCGbo8" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/OcW8qBt" },
    { store: "Funbox 新光三越台中店", region: "台中市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/pmUV4F5" },
    { store: "Funbox 豐原太平洋店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/XOfQ427" },
    { store: "Funbox 豐原太平洋店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/5EBHBfm" },
    { store: "Funbox 豐原太平洋店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/9HXGvi5l" },
    { store: "Funbox 豐原太平洋店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/6Z8wRa4" },
    { store: "Funbox 豐原太平洋店", region: "台中市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/v2OM6vl" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/omR87tZ" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/TNl3ZGd" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/oTNqYqz" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/NSFjbEB" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-18 X旋風發射器", url: "https://lin.ee/X0df3S4" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-26 獨角刺心", url: "https://lin.ee/pvB0Zas" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/obS4tF3" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/uw10pD2" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/sDQaukT" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/n5ZBe5gQ" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-00 暴風天馬", url: "https://lin.ee/xbP7QB9" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-45 武士魂斬", url: "https://lin.ee/unkvnsc" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/7NGpezL" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/VeUYbMY" },
    { store: "Funbox 台中lalaport店", region: "台中市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/zMWwj3Q" },
    // 嘉義市
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/RzrueWr" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/n4lh588" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/WJScw52" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/uWjWAo1" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/zx9seKT" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/RdWwrdUn" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XptkWBX" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/uIAKrOm" },
    { store: "Funbox 嘉義遠東店", region: "嘉義市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/ybPJQ0u" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/pjDJ7QO" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/nKCSoTk" },
    { store: "Funbox 嘉義三越店", region: "嘉義市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/y9P4W2w" },
    // 台東縣
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/rx77vSI" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-45 武士魂斬", url: "https://lin.ee/7L2ZwBZ" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/Ndt9rS0" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/WuDoM99" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/NiUGZMC" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/UrVGwEH" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/9lWh4md" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/Vcn8lNE" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/wWKv6iu" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-33 皓戰猛虎", url: "https://lin.ee/TYbeO2D" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/6Fhvtq5" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XpySyBv" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-26 獨角刺心", url: "https://lin.ee/Z2SzqqaH" },
    { store: "Funbox 台東秀泰店", region: "台東縣", name: "BX-18 X旋風發射器", url: "https://lin.ee/T98JtYO" },
    // 宜蘭縣
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/5UQ9GzU" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/sXZYSWK" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/R6sbF7F" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "UX-20 榮耀武神LF", url: "https://lin.ee/8yFmCkm" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/X8zxJ0Bs" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/oMXVmxD" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-00 暴風天馬", url: "https://lin.ee/wjMbtyi" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/ptDwAc3" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/VUAJFyz" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-18 X旋風發射器", url: "https://lin.ee/plOYnD0" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/X0tCAvI" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-26 獨角刺心", url: "https://lin.ee/u0GANHK" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/Wtp9AQW" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-33 皓戰猛虎", url: "https://lin.ee/sDRDXsw" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/X2qeHZR" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/v6Df1dK" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/xgFmJPXz" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/pUiKS7n" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-45 武士魂斬", url: "https://lin.ee/qYlXm8r" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/wmcRagn" },
    { store: "Funbox 宜蘭新月店", region: "宜蘭縣", name: "UX-15 鮫鯊狂鱗改造組", url: "https://lin.ee/RYuZh5H" },
    // 新竹縣
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-18 X旋風發射器", url: "https://lin.ee/SZ10LFe" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/StHF8FL" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/YBVrhAsv" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-26 獨角刺心", url: "https://lin.ee/upXF1Qv" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/8Nu8BLy" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-33 皓戰猛虎", url: "https://lin.ee/PHR7Ezs" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/pWPSx2t" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/tf7TuZU" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/xtZieLE" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/SMfKXdM" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/QAYR2sw" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/XNK33sO" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/8wN1IHF" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/xeZBWXX" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/Z9pnKPO" },
    { store: "Funbox 竹北遠東店", region: "新竹縣", name: "BX-45 武士魂斬", url: "https://lin.ee/TLoW8e6" },
    // 台南市
    { store: "Funbox 台南新天地店", region: "台南市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/5X4mH1e" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/rHpbeNA" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/wqyUGB7" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BX-26 獨角刺心", url: "https://lin.ee/sgSwGMh" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BX-18 X旋風發射器", url: "https://lin.ee/zPxXYZo" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/WOWijgj" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/SL3z1FN" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/YvJAEm5s" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/q3VeTKK" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/ngtZdnu" },
    { store: "Funbox 台南新天地店", region: "台南市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/WVbuaxc" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-00 暴風天馬", url: "https://lin.ee/6P88wlg" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/8K7fqBn" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-18 X旋風發射器", url: "https://lin.ee/rQivEfl" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/NMSECJv" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-26 獨角刺心", url: "https://lin.ee/te0zeQM" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/NQngBdu" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/wjNb17d" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-37 雙重極限衝擊戰鬥盤豪華組", url: "https://lin.ee/x03sqRv" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/NE7Dwl7u" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-45 武士魂斬", url: "https://lin.ee/5OBDlmX" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/UrgNP13" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/vHQ8iOD" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/oBvdgWL" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/Zt7J2Pn" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/pcVXTlD" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/VhXG0yz" },
    { store: "Funbox 台南南紡店", region: "台南市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/wEbR0Q7" },
    { store: "Funbox 台南三井店", region: "台南市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/7lVBHjH" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/sUMrtwD" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-26 獨角刺心", url: "https://lin.ee/rsKjfva" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/7E0kktq" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/5Z11gMU" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/52gKflo" },
    { store: "Funbox 台南三井店", region: "台南市", name: "BX-18 X旋風發射器", url: "https://lin.ee/s91f6im" },
    { store: "Funbox 台南三井店", region: "台南市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/t5Q7JZ4" },
    // 新竹市
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/XgQ7Frk" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/VHCI3nV" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/RusLNjiQ" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/vXHogcq" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/Wy5ANhK" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/PDuEWPU" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/z8SP0Fc" },
    { store: "Funbox 新竹遠東店", region: "新竹市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/oFWfevv" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/zpKVnDo" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/8yA5lm6" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/7Dc5Y3x" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/6dwXuN0" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/nBfAH4d" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/sxB3FS5" },
    { store: "Funbox 新竹遠雄店", region: "新竹市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/RxZbvrr" },
    // 桃園市
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/PMfRxsS" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-18 X旋風發射器", url: "https://lin.ee/UJOyslk" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-26 獨角刺心", url: "https://lin.ee/Oya4wBN" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/XQtg8KH" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/WHbtrMP" },
    { store: "Funbox 桃園站前三越店", region: "桃園市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/W7a5GSM" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/tM0mVd4" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/TmsRpyR" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/8x5KSVsE" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-00 暴風天馬", url: "https://lin.ee/8ER1QuO" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/nBQY3g3" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-33 皓戰猛虎", url: "https://lin.ee/ZYF4GxZ" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-26 獨角刺心", url: "https://lin.ee/nothX47" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/x955Fpp1" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-18 X旋風發射器", url: "https://lin.ee/VDqoOxe" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-50 天堂日輪隨機強化組", url: "https://lin.ee/6aFQv6D" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "UX-20 榮耀武神LF", url: "https://lin.ee/re25qAN" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/Z8Wd4DP" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/TbNPa1U" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "UX-02 惡魔戰錘", url: "https://lin.ee/zE7aNua" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/OfwqexV" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/zQCD7oi" },
    { store: "Funbox 桃園環球A8店", region: "桃園市", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/pkIvt4V" },
    // 雲林縣
    { store: "來玩聚 斗六店", region: "雲林縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/5l8fVzY" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/pueRSPm" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/xElEriuv" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/U23PQUH" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/y9T89gG" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/P7n3srI" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/zFd3qWy" },
    { store: "來玩聚 斗六店", region: "雲林縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/PhOtSKEG" },
    // 彰化縣
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/xqcKGmu" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/uDpZ8v4" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/ucvku4S" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/nchP1ZV" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-18 X旋風發射器", url: "https://lin.ee/SsUhlWr" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-33 皓戰猛虎", url: "https://lin.ee/8nPSdB1" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/tEjd49I" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "CX-18 腕龍鞭打隨機強化組", url: "https://lin.ee/saXyX60" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-26 獨角刺心", url: "https://lin.ee/UmYEl95" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-35 隨機強化組 Vol.04", url: "https://lin.ee/y2J0AiP" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/7gn97Qyz" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BXG-01 烈焰飛鳳S", url: "https://lin.ee/5nCAF4M" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BXG-04 銀牙烈虎S", url: "https://lin.ee/qCTsbtq" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/6j8mCc5" },
    { store: "來玩聚 彰化店", region: "彰化縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/YmjmECE" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://lin.ee/swdRm0nJ" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://lin.ee/QFBHsVj" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "BX-51 旋風發射器 黑綠", url: "https://lin.ee/onMd6bs" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://lin.ee/npWMFCT" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "UX-02 惡魔戰錘", url: "https://lin.ee/xgwuTzI" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "UX-11 衝擊龍神豪華組", url: "https://lin.ee/OETksPz" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "UX-19 子彈獅鷲H", url: "https://lin.ee/5SbbFz3" },
    { store: "來玩聚 員林店", region: "彰化縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/NaSXCax" },
    // 花蓮縣
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-57 3V3對戰收納盒 黑", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M10Y56SV0W8H2P1Q4MTNSX59?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-25 戰鬥陀螺X專業收納包", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M10YDS10DSSBRCE2S8WFEAKB?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M10YNVW9MRH81XW6EET2BES1?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BBG-31鋼鐵奇兵紀念組$1499", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M110583SHRKET8T5BTVZ97N6?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-26 獨角刺心", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M11090WHK9DR8QDR9SZYKFE3?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-40 左迴旋發射器 酒紅", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M110HGWGRJN4APY8B565RSQQ?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BXG-04 銀牙烈虎S", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M110NBVMERP582E8G538PG65?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BXG-01 烈焰飛鳳S", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M110RC9989TR5X3XBA55KNCH?q=timeline_post" },
    { store: "Funbox 花蓮店", region: "花蓮縣", name: "BX-45 武士魂斬", url: "https://liff.line.me/1654883387-DxN9w07M/c/01M113ACRMJJ03M6531Q4C3GEF?q=timeline_post" },
    // 澎湖縣
    { store: "Funbox 澎湖3號港店", region: "澎湖縣", name: "UX-04 極限衝擊對戰組U", url: "https://lin.ee/Vy6fpBO" },
    { store: "Funbox 澎湖3號港店", region: "澎湖縣", name: "BX-10 極限衝擊戰鬥盤", url: "https://lin.ee/7tvz4ay" },
    { store: "Funbox 澎湖3號港店", region: "澎湖縣", name: "BX-32 寬型極限衝擊戰鬥盤", url: "https://lin.ee/NogiHFe" },
];
